MyBiasPhoto/7-MyBiasPhoto-team1-FE

app/layout.js, components/header/Alarm.js, components/header/Alarm.module.css, components/header/Header.js, components/header/Header.module.css, components/header/NotLogin.js, components/header/NotLogin.module.css, components/header/SideAlarm.js, components/header/SideAlarm.module.css, components/header/SideMenu.js, components/header/SideMenu.module.css, components/header/UserInfo.js, components/header/UserInfo.module.css, components/header/UserMenu.js, components/header/UserMenu.module.css, utils/Providers.js
navbar 임시 구현 및 반응형 CSS 구현
알림창 임시 구현 및 반응형 CSS 구현
프로필창 임시 구현 및 반응형 CSS 구현
=> navBar & 알림창 & 프로필창 임시 구현 #2 #22 #23

app/login/page.js, app/login/page.module.css, app/signup/page.js, app/signup/page.module.css
=> login, signup 페이지 추가

components/header/RandomBox.js, components/header/RandomBox.module.css, components/header/RandomModal.js, components/header/RandomModal.module.css, components/header/SideMenu.js, components/header/SideMenu.module.css, components/header/UserMenu.js, components/header/UserMenu.module.css
=> 랜덤 포인트 모달 및 코드 구현(임시) #21

app/myGallery/MyGalleryClient.js, app/myGallery/page.js, app/wjtest/ClientComponent.js, app/wjtest/page.js, app/wjtestTwo/SaleList.js, app/wjtestTwo/page.js, components/common/FilterBar.js, components/header/Header.js, components/loadingSpinner/LoadingSpinner.js, components/loadingSpinner/LoadingSpinner.module.css, components/myGallery/MyGalleryCardGrid.js, utils/api/myGalleries.js, utils/api/sales.js
=> MyGallery 추가 머지용 pr

app/marketPlace/[id]/page.js, app/marketPlace/[id]/page.module.css, app/marketPlace/page.js, app/marketPlace/page.module.css, components/marketPlace/card/card.js, components/marketPlace/card/card.module.css, components/marketPlace/customInput/customInput.js, components/marketPlace/customInput/customInput.module.css, components/marketPlace/section/buy/buy.js, components/marketPlace/section/buy/buy.module.css, components/marketPlace/section/tradeList/tradeList.js, components/marketPlace/section/tradeList/tradeList.module.css, components/marketPlace/section/tradeinfo/tradeinfo.js, components/marketPlace/section/tradeinfo/tradeinfo.module.css, components/marketPlace/select/select.js, components/marketPlace/select/select.module.css, components/marketPlace/tradeCard/tradeCard.js, components/marketPlace/tradeCard/tradeCard.module.css
=> Feat/marketplace 마켓플레이스 구매 UI 구현

app/page.js, components/modals/sellPhotoModal.js, components/modals/sellPhotoModal.module.css
=> docs: sellPhotoModal 관련 파일 수정 및 추가 #7 #8

components/modals/exchangePhotoModal.js, components/modals/exchangePhotoModal.module.css, components/modals/exchangeResultModal.js, components/modals/sellPhotoModal.js, components/modals/sellPhotoModal.module.css, components/modals/sellResultModal.js
feat: 판매 교환 모달 api 연결과 기능 추가 및 관련 파일 수정 #7 #8 #9 #12 #13
=> feat: 판매 교환 모달 api 연결과 기능 추가 및 관련 파일 수정 #7 #8 #9 #12 #13

app/page.js, components/modals/card/ModalCard.js, components/modals/card/ModalCard.module.css, components/modals/exchangePhotoModal.js, components/modals/exchangePhotoModal.module.css, components/modals/sellPhotoModal.js, components/modals/sellPhotoModal.module.css
feat: 판매하기 교환하기 모달 반응형 1차 적용 및 모달카드 추가 #7 #8 #12 #13
=> feat: 판매하기 교환하기 모달 반응형 1차 적용 및 모달카드 추가 #7 #8 #12 #13

app/marketPlace/page.js, app/marketPlace/page.module.css, components/marketPlace/card/card.js, components/marketPlace/card/card.module.css, components/marketPlace/config/config.js, components/marketPlace/edit/card/card.js, components/marketPlace/edit/section/edit.js, components/marketPlace/edit/tradeList/tradeList.js, components/marketPlace/section/buy/buy.js, components/marketPlace/section/landing/cardList/CardList.js, components/marketPlace/section/landing/filterBar/FilterBar.js, components/marketPlace/section/landing/filterModal/FilterModal.js, components/marketPlace/section/tradeList/tradeList.js, components/marketPlace/section/tradeinfo/tradeinfo.js, components/marketPlace/tradeCard/tradeCard.js, utils/api/marketPlace.js
=> Feat/marketplace 임시로직구현 및 병합을위한 pr

components/modals/exchangePhotoModal.js, components/modals/exchangeResultModal.js, utils/api/exchange.js
=> feat: 교환 api 관련 파일 수정 및 추가

lib/axiosAuth.js, utils/auth/authContext.js
로그인 페이지 강제 이동 및 새로고침 무한 루프 버그 수정
=> 리프레시 무한 루프 오류 수정 #3

app/marketPlace/page.js, components/marketPlace/card/card.js, components/marketPlace/customInput/customInput.js, components/marketPlace/edit/section/edit.js, components/marketPlace/section/buy/buy.js, components/marketPlace/section/landing/filterModal/FilterModal.js, components/modals/editPhotoModal.js, utils/api/marketPlace.js
=> Feat/marketplace  edit 로직수정

app/myGallery/create/page.js, app/myGallery/create/page.module.css, components/myGallery/photoCardCreate/CreateInput.js, components/myGallery/photoCardCreate/CreateSelect.js, components/myGallery/photoCardCreate/CreateTextarea.js, components/myGallery/photoCardCreate/CreateUpload.js, next.config.mjs
AWS S3 업로드 방식으로 변경 및 월 생성제한 중복업로드 방지 #18
=> AWS S3 업로드 방식으로 변경 및 월 생성제한 중복업로드 방지 #18

app/marketPlace/[id]/edit/page.js, components/marketPlace/edit/card/card.js, components/marketPlace/edit/tradeList/tradeList.js, components/marketPlace/section/tradeList/tradeList.js, components/marketPlace/section/tradeinfo/tradeinfo.js, components/marketPlace/tradeCard/tradeCard.js, components/modals/exchangeApproveModal.js, components/modals/exchangeCancelModal.js, components/modals/exchangeCancelModal.module.css, components/modals/exchangePhotoModal.js, components/modals/exchangeRefuseModal.js
=> feat: 교환 api 프론트 완료 (진짜임)

components/modals/purchasePhotoModal.js, components/modals/purchaseResultModal.js
feat: 구매 모달 버튼 submitting 및 쿼리 무효 추가 #11
=> feat: 구매 모달 버튼 submitting 및 쿼리 무효 추가 #11

components/header/RandomBox.js, components/header/SideMenu.js, components/header/UserMenu.js, utils/Providers.js, utils/auth/authContext.js, utils/cooldown/cooldownContext.js
=> 랜덤 포인트 쿨다운 API 연결 및 CSS 수정 #2 #21

app/mySale/MySaleClient.js, app/mySale/page.module.css, components/common/CardRarityCount/CardRarityCountList.module.css, components/common/contentHeader/ContentHeader.module.css, components/common/filter/SearchInput.module.css, components/common/userCard/UserCardItem.js, components/common/userCard/UserCardList.module.css, components/mySalePage/FilterContainer.module.css
=> 나의 판매 포토카드 css #20

app/myGallery/create/page.js, app/myGallery/create/page.module.css
포토카드 생성 페이지 월간 남은 장 표시 수정 및 반응형 css 수정 #18
=> 포토카드 생성 페이지 월간 남은 장 표시 수정 및 반응형 css 수정 #18

app/globals.css, components/header/Alarm.module.css
=> feat(alarm): alarm css #22

components/header/Alarm.js, components/header/Alarm.module.css, components/marketPlace/card/card.js, utils/api/notification.js, utils/formatTimeAgo.js, utils/notifications/notificationsContext.js
fix(notification): 알림창 무한스크롤 구현 #22
=> fix(notification): 알림창 무한스크롤 구현 #22

app/marketPlace/[id]/edit/page.js, components/marketPlace/edit/tradeList/tradeList.js, components/marketPlace/section/tradeList/tradeList.js, components/modals/exchangePhotoModal.js, components/modals/exchangePhotoModal.module.css, components/modals/sellCancelModal.module.css, components/modals/sellPhotoModal.js, components/modals/state/ModalState.js, components/modals/state/ModalState.module.css
=> feat: ModalState 추가 및 코드 수정

app/api/aiImage/route.js, app/myGallery/create/page.js, app/myGallery/create/page.module.css, components/myGallery/photoCardCreate/CreateSelect.js, package-lock.json, package.json
=> 포토카드 ai 이미지 생성 #99

components/header/Alarm.js, components/header/Alarm.module.css, components/header/AlarmSkeleton.js, components/header/SideAlarm.js, components/header/SideAlarm.module.css, utils/api/notification.js, utils/notifications/notificationsContext.js
=> 알림 css + Side알림 기능구현

app/marketPlace/[id]/edit/page.module.css, app/marketPlace/[id]/page.module.css, app/myGallery/create/page.module.css, components/marketPlace/edit/area/editTrade.module.css, components/marketPlace/edit/section/edit.module.css, components/marketPlace/section/buy/buy.module.css
포토카드 상세페이지 구매자,판매자 반응형 css #10 #14
=> 포토카드 상세페이지 구매자,판매자 반응형 css #10 #14

components/modals/editPhotoModal.js
=> feat: 수정하기 모달 등급 컬러 반영 수정

components/modals/sellPhotoModal.js
fix: sellPhotoModal.js 코드 수정 찐막
모바일 필터 관련~
=> fix: sellPhotoModal.js 코드 수정 찐막
